import test from "node:test";
import assert from "node:assert/strict";
import { chmod, mkdtemp, mkdir, readFile, readdir, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  brokenPiSpawnerMarketplaceNames,
  buildClaudeMarketplace,
  buildCodexMarketplace,
  codexListHasInstalledPlugin,
  ensureCodexPersonalPlugin,
  installHost
} from "./adapters.js";

test("buildCodexMarketplace creates personal marketplace entry", () => {
  const { name, payload } = buildCodexMarketplace({});

  assert.equal(name, "personal");
  assert.equal(payload.name, "personal");
  assert.deepEqual(payload.interface, { displayName: "Personal" });
  assert.deepEqual(payload.plugins, [
    {
      name: "pi-spawner",
      source: {
        source: "local",
        path: "./plugins/pi-spawner"
      },
      policy: {
        installation: "AVAILABLE",
        authentication: "ON_INSTALL"
      },
      category: "Productivity"
    }
  ]);
});

test("buildCodexMarketplace preserves marketplace name and replaces stale entry", () => {
  const { name, payload } = buildCodexMarketplace({
    name: "personal-dev",
    interface: {
      displayName: "Personal Dev"
    },
    plugins: [
      {
        name: "other",
        source: {
          source: "local",
          path: "./plugins/other"
        }
      },
      {
        name: "pi-spawner",
        source: {
          source: "local",
          path: "./old"
        }
      }
    ]
  });

  assert.equal(name, "personal-dev");
  assert.deepEqual(payload.interface, { displayName: "Personal Dev" });
  const plugins = payload.plugins;
  assert.ok(Array.isArray(plugins));
  assert.equal(plugins.length, 2);
  assert.deepEqual(plugins[1], {
    name: "pi-spawner",
    source: {
      source: "local",
      path: "./plugins/pi-spawner"
    },
    policy: {
      installation: "AVAILABLE",
      authentication: "ON_INSTALL"
    },
    category: "Productivity"
  });
});

test("buildClaudeMarketplace creates Claude local marketplace shape", () => {
  const marketplace = buildClaudeMarketplace("pi-spawner");

  assert.equal(marketplace.name, "pi-spawner");
  assert.deepEqual(marketplace.owner, { name: "Johnny Bae" });
  assert.deepEqual(marketplace.plugins, [
    {
      name: "pi-spawner",
      source: "./plugins/pi-spawner",
      description: "Delegate work to Pi model workers through the global pi-spawner CLI",
      version: "0.4.0",
      category: "Productivity"
    }
  ]);
});

test("ensureCodexPersonalPlugin refuses to overwrite unrelated plugin directory", async () => {
  const previousHome = process.env.HOME;
  const previousPiSpawnerHome = process.env.PI_SPAWNER_HOME;
  const home = await mkdtemp(join(tmpdir(), "pi-spawner-home-"));
  const state = await mkdtemp(join(tmpdir(), "pi-spawner-state-"));
  try {
    process.env.HOME = home;
    process.env.PI_SPAWNER_HOME = state;
    const pluginRoot = join(home, "plugins", "pi-spawner");
    await mkdir(pluginRoot, { recursive: true });
    await writeFile(join(pluginRoot, "README.md"), "not generated by pi-spawner\n", "utf8");

    await assert.rejects(
      () => ensureCodexPersonalPlugin("pi-spawner"),
      /already exists and is not a Pi Spawner plugin/
    );
  } finally {
    if (previousHome === undefined) {
      delete process.env.HOME;
    } else {
      process.env.HOME = previousHome;
    }
    if (previousPiSpawnerHome === undefined) {
      delete process.env.PI_SPAWNER_HOME;
    } else {
      process.env.PI_SPAWNER_HOME = previousPiSpawnerHome;
    }
    await rm(home, { recursive: true, force: true });
    await rm(state, { recursive: true, force: true });
  }
});

test("ensureCodexPersonalPlugin refuses same-name non-Pi Spawner plugin manifests", async () => {
  await withTempHome(async (home) => {
    const pluginRoot = join(home, "plugins", "pi-spawner");
    await mkdir(join(pluginRoot, ".codex-plugin"), { recursive: true });
    await writeFile(
      join(pluginRoot, ".codex-plugin", "plugin.json"),
      `${JSON.stringify({ name: "pi-spawner", description: "A different local plugin" }, null, 2)}\n`,
      "utf8"
    );

    await assert.rejects(
      () => ensureCodexPersonalPlugin("pi-spawner"),
      /already contains a different Codex plugin/
    );
  });
});

test("ensureCodexPersonalPlugin backs up malformed personal marketplace JSON", async () => {
  await withTempHome(async (home) => {
    const marketplaceDir = join(home, ".agents", "plugins");
    await mkdir(marketplaceDir, { recursive: true });
    await writeFile(join(marketplaceDir, "marketplace.json"), "{ invalid json\n", "utf8");

    await ensureCodexPersonalPlugin("pi-spawner");

    const entries = await readdir(marketplaceDir);
    assert.ok(entries.some((entry) => entry.startsWith("marketplace.json.invalid-")));
    const marketplace = JSON.parse(await readFile(join(marketplaceDir, "marketplace.json"), "utf8"));
    assert.equal(marketplace.name, "personal");
    assert.equal(marketplace.plugins[0].name, "pi-spawner");
  });
});

test("brokenPiSpawnerMarketplaceNames only returns the Pi Spawner broken marketplace", () => {
  const names = brokenPiSpawnerMarketplaceNames({
    ok: false,
    stdout: "",
    stderr: [
      "Error: failed to load marketplace(s):",
      "- `pi-spawner` at /tmp/pi-spawner: marketplace root does not contain a supported manifest",
      "- `other` at /tmp/other: marketplace root does not contain a supported manifest"
    ].join("\n"),
    exitCode: 1
  });

  assert.deepEqual(names, ["pi-spawner"]);
});

test("codexListHasInstalledPlugin parses nested plugin list JSON", () => {
  const stdout = JSON.stringify({
    marketplaces: [
      {
        name: "personal",
        plugins: [
          {
            name: "pi-spawner",
            marketplaceName: "personal",
            installed: true
          }
        ]
      }
    ]
  });

  assert.equal(codexListHasInstalledPlugin(stdout, "personal"), true);
  assert.equal(codexListHasInstalledPlugin(stdout, "team"), false);
});

test("installHost repairs a broken Codex pi-spawner marketplace before installing", async () => {
  await withTempInstallEnv(async (_home, _state, bin, logPath) => {
    await writeExecutable(join(bin, "codex"), `#!/bin/sh
printf '%s\\n' "$*" >> "$FAKE_LOG"
if [ "$1 $2" = "plugin list" ]; then
  echo 'Error: failed to load marketplace(s):' >&2
  echo '- \`pi-spawner\` at /tmp/pi-spawner: marketplace root does not contain a supported manifest' >&2
  exit 1
fi
if [ "$1 $2 $3" = "plugin marketplace remove" ]; then
  echo '{"removed":true}'
  exit 0
fi
if [ "$1 $2" = "plugin add" ]; then
  echo '{"installed":true}'
  exit 0
fi
exit 2
`);

    const result = await installHost("codex", { repairBrokenCodexMarketplace: true });

    assert.equal(result.ok, true);
    const log = await readFile(logPath, "utf8");
    assert.match(log, /plugin marketplace remove pi-spawner --json/);
    assert.match(log, /plugin add pi-spawner@personal --json/);
  });
});

test("installHost treats existing Claude marketplace and plugin as success", async () => {
  await withTempInstallEnv(async (_home, _state, bin) => {
    await writeExecutable(join(bin, "claude"), `#!/bin/sh
if [ "$1 $2 $3" = "plugin marketplace add" ]; then
  echo 'marketplace already exists' >&2
  exit 1
fi
if [ "$1 $2" = "plugin install" ]; then
  echo 'plugin already installed' >&2
  exit 1
fi
exit 2
`);

    const result = await installHost("claude-code");

    assert.equal(result.ok, true);
    assert.match(result.detail, /Installed from/);
  });
});

test("installHost refuses to replace a Cursor symlink that points elsewhere", async () => {
  await withTempHome(async (home) => {
    const target = join(home, ".cursor", "plugins", "local", "pi-spawner");
    await mkdir(join(home, ".cursor", "plugins", "local"), { recursive: true });
    await symlink("/tmp/some-other-plugin", target, "dir");

    const result = await installHost("cursor");

    assert.equal(result.ok, false);
    assert.match(result.detail, /already points to a different plugin/);
  });
});

async function withTempHome(callback: (home: string, state: string) => Promise<void>): Promise<void> {
  const previousHome = process.env.HOME;
  const previousPiSpawnerHome = process.env.PI_SPAWNER_HOME;
  const home = await mkdtemp(join(tmpdir(), "pi-spawner-home-"));
  const state = await mkdtemp(join(tmpdir(), "pi-spawner-state-"));
  try {
    process.env.HOME = home;
    process.env.PI_SPAWNER_HOME = state;
    await callback(home, state);
  } finally {
    if (previousHome === undefined) {
      delete process.env.HOME;
    } else {
      process.env.HOME = previousHome;
    }
    if (previousPiSpawnerHome === undefined) {
      delete process.env.PI_SPAWNER_HOME;
    } else {
      process.env.PI_SPAWNER_HOME = previousPiSpawnerHome;
    }
    await rm(home, { recursive: true, force: true });
    await rm(state, { recursive: true, force: true });
  }
}

async function withTempInstallEnv(callback: (home: string, state: string, bin: string, logPath: string) => Promise<void>): Promise<void> {
  const previousPath = process.env.PATH;
  const previousFakeLog = process.env.FAKE_LOG;
  await withTempHome(async (home, state) => {
    const bin = await mkdtemp(join(tmpdir(), "pi-spawner-bin-"));
    const logPath = join(home, "commands.log");
    try {
      process.env.PATH = `${bin}:${previousPath || ""}`;
      process.env.FAKE_LOG = logPath;
      await callback(home, state, bin, logPath);
    } finally {
      if (previousPath === undefined) {
        delete process.env.PATH;
      } else {
        process.env.PATH = previousPath;
      }
      if (previousFakeLog === undefined) {
        delete process.env.FAKE_LOG;
      } else {
        process.env.FAKE_LOG = previousFakeLog;
      }
      await rm(bin, { recursive: true, force: true });
    }
  });
}

async function writeExecutable(path: string, contents: string): Promise<void> {
  await writeFile(path, contents, "utf8");
  await chmod(path, 0o755);
}
